parameters:
  env(PRESENTER_EXPAND_KEY): 'expand'
  env(PRESENTER_FILTER_KEY): 'filter'
  env(PRESENTER_SORT_KEY): 'sort'
  env(PRESENTER_PAGE_KEY): 'page'
  env(PRESENTER_PAGE_SIZE_KEY): 'page_size'
  env(PRESENTER_DEFAULT_PAGE_SIZE): '25'
  env(PRESENTER_PAGE_START): '1'

  presenter.expand_key: '%env(PRESENTER_EXPAND_KEY)%'
  presenter.filter_key: '%env(PRESENTER_FILTER_KEY)%'
  presenter.sort_key: '%env(PRESENTER_SORT_KEY)%'
  presenter.page_key: '%env(PRESENTER_PAGE_KEY)%'
  presenter.page_size_key: '%env(PRESENTER_PAGE_SIZE_KEY)%'
  presenter.default_page_size: '%env(int:PRESENTER_DEFAULT_PAGE_SIZE)%'
  presenter.page_start: '%env(int:PRESENTER_PAGE_START)%'

services:
  _defaults:
    autowire: true


  Platim\PresenterBundle\ArgumentResolver\PresenterResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Platim\PresenterBundle\ArgumentResolver\RequestArgumentResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Platim\PresenterBundle\Request\Expand\ExpandFactory:
    arguments:
      $expandKey: '%presenter.expand_key%'

  Platim\PresenterBundle\Request\Sort\SortFactory:
    arguments:
      $sortKey: '%presenter.sort_key%'

  Platim\PresenterBundle\Request\Pagination\PaginationRequestFactory:
    arguments:
      $pageKey: '%presenter.page_key%'
      $pageSizeKey: '%presenter.page_size_key%'
      $defaultPageSize: '%presenter.default_page_size%'
      $pageStart: '%presenter.page_start%'

  Platim\PresenterBundle\Request\Filter\FilterFactory:
    arguments:
      $ignored:
        - '%presenter.sort_key%'
        - '%presenter.expand_key%'
        - '%presenter.page_key%'
        - '%presenter.page_size_key%'

  Platim\PresenterBundle\PresenterContext\DataProviderContextFactory: ~
  Platim\PresenterBundle\PresenterContext\ObjectContextFactory: ~

  Platim\PresenterBundle\PresenterHandler\PresenterHandlerRegistry: ~
  Platim\PresenterBundle\NameConverter\NameConverterRegistry: ~
  Platim\PresenterBundle\DoctrineInteraction\MetadataRegistry: ~

  Platim\PresenterBundle\Serializer\ObjectNormalizer:
    tags:
      - { name: serializer.normalizer, priority: 50 }

  Platim\PresenterBundle\Serializer\DataProviderNormalizer:
    tags:
      - { name: serializer.normalizer, priority: 100 }